### ISSUE TITLE
Minibatch size & weighing factor

### ISSUE THREAD

**Issue by sidml** [wiseodd/last_layer_laplace#6]
I was wondering what is the recommended mini batch size (m) and weight factor. (rho) 

![image](https://user-images.githubusercontent.com/51043033/103730457-e3241b00-501d-11eb-8d99-ec34cf13f5de.png)

**Comment by wiseodd** [comment]
Hi, sorry for the delay. In our experiments we use minibatch size of 128 and \rho following the original K-FAC: https://arxiv.org/abs/1503.05671. But I think \rho of 0.9 should do just fine.
