### ISSUE TITLE
Does it make sense to use both LLLA and temperature scaling together?

### ISSUE THREAD

**Issue by YanDavKMS** [wiseodd/last_layer_laplace#7]
and if so in what order, first temperature scaling and then LLLA or vice versa?

**Comment by wiseodd** [comment]
Yes, it makes sense---after all, the temperature scaling can be seen as tempering your likelihood. To do it correctly, you have to apply it in all places where the likelihood is used. This can be done easily via our new library https://github.com/AlexImmer/Laplace.

**Comment by YanDavKMS** [comment]
Hey,

Sorry for the late response and thank you for your help.
I'm not sure if I should write my next question here or in the new library repo.

Is this the temperature you meant for temperature scaling?
```
temperature : float, default=1
        temperature of the likelihood; lower temperature leads to more
        concentrated posterior and vice versa.
```

and if not, can you please direct me on how to apply the temperature scaling?
Just to make sure, I'm talking about [temperature scaling](https://github.com/gpleiss/temperature_scaling) for calibration
